#pragma once

#include "quantum.h"

/* =========================================================================
 * Layer indices
 * ========================================================================= */
enum mercurio_layers {
    _BASE,
    _LOWER,
    _RAISE,
    _ADJUST,
};

/* =========================================================================
 * Key matrix layout
 *
 * LAYOUT is generated by QMK from the keyboard.json `layouts` section.
 * Do not redefine it here.
 *
 * P0 / P1  — single half (5 rows × 7 cols = 35 keys, split_keyboard off).
 * P2 onward — keyboard.json layouts and matrix_pins are updated to the
 *             full split layout (10 rows × 7 cols = 70 keys).
 * ========================================================================= */

/* =========================================================================
 * Split shared state
 *
 * Synchronized Master → Slave on every USART transport cycle (FR-06).
 *
 * IMPORTANT: field order is part of the wire protocol — never reorder or
 * remove fields after P2.  Append-only growth is safe.
 * ========================================================================= */
typedef struct {
    uint8_t  active_layer;      /* 0–15                                      */
    uint8_t  led_brightness;    /* 0–100 (%, post-LDR scaling)               */
    uint8_t  audio_volume;      /* 0–100                                     */
    bool     caps_lock;
    bool     num_lock;
    bool     scroll_lock;
    uint8_t  piezo_ocr2;        /* Timer2 OCR2 for slave note (0 = silent)   */
    uint8_t  piezo_duration_ms; /* slave note duration in ms                 */
    bool     ldr_enabled;       /* LDR auto-dimming on/off; EEPROM-persisted */
    int8_t   ldr_cal_offset;    /* slave LDR cal offset (ADC units, signed)  */
} mercurio_split_state_t;

extern mercurio_split_state_t mercurio_state;

/* Split transaction ID — enable in P2 when split_keyboard is turned on.
 * Requires the split-transaction enum from QMK's split framework.
 *
 * #define SPLIT_TRANSACTION_IDS_USER MERCURIO_STATE_SYNC
 */
